INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (1,'Jefe de Aeropuerto Colombia');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (2,'Especialista Comercial Colombia');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (3,'Encargado Administrativo Aeropuerto Colombia');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (4,'Coordinador Aeropuerto SJO');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (5,'Jefe Operaciones Terrestres Despacho CAM');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (6,'Asistente Administrativo');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (7,'Coordinador AVSEC SJO');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (8,'Instructor AVSEC CAM');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (9,'Jefe de Cabina');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (11,'Jefe de SCM RP');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (12,'Capitan');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (13,'Despachador');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (14,'Jefe Mantenimiento CAM');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (15,'Especialista IT CAM');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (16,'Gerente Aseguramiento Calidad CAM');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (17,'Supervisor Mantenimiento CAM');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (18,'Supervisor Almacen CAM');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (19,'Jefe Adiestramiento Pilotos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (20,'Gerente Operaciones SJO');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (21,'Copiloto');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (22,'Ingeniero Planeacion SJO');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (23,'Almacenista Tecnico');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (24,'Investigador Seguridad Operacional SJO');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (25,'Copiloto Becario');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (26,'Encargado Administrativo Aeropuerto');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (27,'Sobrecargo Mentor');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (28,'Inspector Control Calidad CAM');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (29,'Lider Administrativo CAM');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (30,'Especialista Compras Generales');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (31,'Sobrecargo Senior');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (32,'Instructor Capacitacion Sobrecargos SJO');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (34,'Jefe Sobrecargos SJO');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (35,'Jefe Pilotos SJO');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (36,'Jefe Control Calidad CAM');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (37,'Especialista Comercial');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (38,'Auditor Aseguramiento Calidad SJO');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (39,'Jefe Aeropuerto SJO');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (40,'Especialista Cuentas Por Pagar');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (41,'Director Relaciones Institucionales CAM');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (42,'Lider Capacitacion CAM');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (43,'Gerente Sr Comercial CAM');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (44,'Lider Carga Aerea CAM');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (45,'Analista Control Tripulaciones');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (46,'Ingeniero Operaciones');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (47,'Sobrecargo Junior');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (48,'Especialista Contabilidad Reporteo');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (49,'Abogado Sr CAM');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (50,'Director Transporte Aereo');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (51,'Lider Control Operaciones Cargo SJO');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (52,'Jefe de Ventas CAM/SAM');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (53,'Coordinador AVSEC');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (54,'Jefe de Aeropuerto Guatemala');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (55,'Lider Control Operaciones Cargo GUA');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (56,'Jefe Aeropuerto LIM');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (57,'Encargada Administrativa');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (58,'Gerente Operaciones SAL');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (59,'Gerente SMS SAL');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (60,'Jefe Sobrecargos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (61,'Jefe AVSEC SAL');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (62,'Jefe Mantenimiento SAL');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (63,'Jefe Sr QA SAL');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (64,'Analista Publicaciones Tecnicas');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (65,'Jefe Aeropuerto SAL');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (66,'Jefe Cabina');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (67,'Sobrecargo Asesor');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (68,'Jefe de Estandares de Vuelo SAL');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (69,'Jefe Control Calidad');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (70,'Jefe Despacho y NavData Analysis');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (71,'Jefe Pilotos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (72,'Ingeniero Planeacion');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (73,'Auditor Aseguramiento Calidad SAL');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (74,'Investigador Seguridad Operacional SAL');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (75,'Especialista Marketing CAM SAM');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (76,'Instructor Capacitacion Sobrecargos SAL');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (77,'Abogado Sr SAL');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (78,'Encargado Administrativo Aeropuerto SAL');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (79,'Supervisor Mantenimiento SAL');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (80,'Inspector Control Calidad SAL');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (81,'Supervisor Abastecimiento Critico SAL');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (82,'Supervisor Almacen SAL');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (83,'Analista Almacen');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (84,'Coordinador Servicios Mayores');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (85,'Analista Control Procesos Internacionales Carga');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (86,'Presidente Ejecutivo y Director General');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (87,'Jefe Seguridad Aviacion');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (88,'Analista Capacitacion Aeropuertos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (89,'Gerente Capacitacion Pilotos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (90,'Gerente Estandares Vuelo');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (91,'Jefe Sr Ingresos Consolidados e Interlineales');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (92,'Gerente Sr Tecnico Comercial');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (93,'Director Sobrecargos y Servicio a Bordo');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (94,'Supervisor Mantenimiento CCM');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (95,'Jefe Sr Capacitacion y Normatividad Sobrecargos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (96,'Instructor Capacitacion Sobrecargos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (97,'Mecanico');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (98,'Coordinador Operaciones Terrestres');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (99,'Jefe Sr Centro Control Operacional');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (100,'Jefe Sr Despacho');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (101,'Jefe Despacho');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (102,'Asesor Lead');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (103,'Lider Prevencion Fraude y Aseguramiento Ingresos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (104,'Gerente Sr Soporte Operativo');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (105,'Gerente Sr Asuntos Regulatorios');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (106,'Lider Administracion Aeropuertos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (107,'Vicepresidente Sr Operaciones');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (108,'Gerente Operaciones Tierra');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (109,'Jefe Aeropuerto TIJ');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (110,'Director Sr Comercial');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (111,'Lider Capacitacion Inicial Sobrecargos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (112,'Gerente Sr Fiscal');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (113,'Director Sr Flota y Compras');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (114,'Inspector Control Calidad');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (115,'Jefe Aeropuerto');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (116,'Jefe Planeacion Rosters');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (117,'Agente Apariencia');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (118,'Instructor Capacitacion Servicio al Cliente');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (119,'Inspector Recibo e Inspeccion');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (120,'Inspector Control Calidad NDT');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (121,'Supervisor Almacen Comisariato');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (122,'Jefe Servicio al Cliente');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (123,'Tecnico Taller');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (124,'Gerente Aeropuerto TIJ');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (125,'Especialista Estandares Aeropuertos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (126,'Gerente Soporte Operativo TIJ');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (127,'Supervisor Apariencia');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (128,'Director Sr Tecnologia y Transformacion');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (129,'Coordinador Apariencia');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (130,'Gerente Sr Aseguramiento Calidad y Seguridad Operacional');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (131,'Gerente Sr Planeacion de Rutas');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (132,'Gerente Compras Directas');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (133,'Agente Coach');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (134,'Gerente Incorporacion Transferencia y Devolucion Aeronaves');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (135,'Jefe Operaciones Terrestres AICM');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (136,'Gerente Sr Ingenieria Operaciones');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (137,'Supervisor AORs');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (138,'Gerente Aeropuerto CUN');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (139,'Gerente Sr Operaciones Vuelo');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (140,'Jefe Sr Pilotos Sistema');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (141,'Gerente Marketing Disruptivo Atraccion Clientes y CAM');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (142,'Gerente Contabilidad Ingresos y Prevencion Fraude');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (143,'Supervisor Mantenimiento');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (144,'Lider Planeacion Adiestramiento');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (145,'Analista Reparaciones Core Return');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (146,'Especialista Motores');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (147,'Jefe Sr Ingenieria Motores');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (148,'Especialista Control Tripulaciones');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (149,'Gerente Atraccion Talento');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (150,'Supervisor Interiores');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (151,'Gerente Auditoria Operacional y Fraude');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (152,'Gerente Total Cost of Ownership');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (153,'Gerente Soporte Operaciones Vuelo');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (154,'Jefe Ventas MEX - EEUU');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (155,'Jefe Sr Ingenieria Procedimientos y Normas');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (156,'Gerente Sr Procesos Legales y Contratos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (157,'Gerente Sr Contabilidad y Administracion');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (158,'Jefe Regional Pilotos Este');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (159,'Gerente Regional Aeropuertos GAP');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (160,'Gerente Regional Sobrecargos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (161,'Tecnico Seguridad Aeroportuaria');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (162,'Lider Control Gestion Aeropuertos HUBs');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (163,'Tecnico Monitoreo');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (164,'Supervisor Hub Control');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (165,'Gerente Sr Aplicaciones Operaciones y Combustible');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (166,'Jefe Sr Contabilidad Mantenimiento');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (167,'Agente Trafico');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (168,'Analista Precios');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (169,'Especialista Administracion Ingresos Domesticos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (170,'Reclutador');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (171,'Tecnico Mecanico');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (172,'Operador Equipo');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (173,'Asesor Lead Equipajes');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (174,'Especialista Control Gestion Costeo y Modelo Aeropuertos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (175,'Analista Control Produccion Hangar');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (176,'Lider Planeacion Medios Digitales');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (177,'Especialista Airpas');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (178,'Especialista Gobierno');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (179,'Operations Digital Products Analyst');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (180,'Abogado Sr');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (181,'Especialista Producto');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (182,'Director Contraloria y Cumplimiento');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (183,'Analista Administracion Ingresos Domesticos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (184,'Lider Control Produccion');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (185,'Supervisor Almacen');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (186,'Especialista Seguridad Ejecutiva');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (187,'Sobrecargo Becario');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (188,'Jefe Sr Filiales y CCT');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (189,'Coordinador ACDM');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (190,'Mecanico Interiores');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (191,'Asesor Operaciones Rampa');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (192,'Agente Monitoreo');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (193,'Analista Redes Sociales y Contenido');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (194,'Ingeniero Procedimientos y Normas CGO');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (195,'Jefe Compensaciones');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (196,'Analista Sistema SMARTKARGO COMAT');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (197,'Lider Precios Transferencia');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (198,'Lider People Partner Operation');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (199,'Especialista Comunicacion Institucional y Cultura');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (200,'Especialista Mantenimiento');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (201,'Especialista Cultura');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (202,'Lider Erogaciones Aeropuestos Nacionales');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (203,'Ingeniero Control Produccion');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (204,'Asesor CSA');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (205,'Coordinador Equipajes AICM');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (206,'Especialista Planeacion Tripulaciones');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (207,'Especialista Planeacion de Rutas');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (208,'Especialista Modelos y Tarifa Base Dinamica');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (209,'Gerente AICM');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (210,'Lider Cultura');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (211,'Analista Control Calidad');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (212,'Ingeniero Administracion Aeronaves');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (213,'Especialista Devolucion Aeronaves');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (214,'Jefe Control Produccion');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (215,'Inspector Control Calidad Hangar');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (216,'Jefe Sr Entrega Servicio Al Cliente');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (217,'Lider Proyectos Especiales DG');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (218,'Auditor Sr Operaciones');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (219,'Especialista Administracion Productos Adicionales');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (220,'Director Compras');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (221,'Gerente Sr Abastecimientos y Relacion Tecnica Arrendadores');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (222,'Gerente Sr Mantenimiento y Control Calidad');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (223,'Jefe Mantenimiento A-SCV');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (224,'Analista Funcional');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (225,'Analista Administracion Tripulaciones');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (226,'Especialista Performance Marketing');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (227,'Especialista Revenue Management Domestico TIJ, BJX, MTY');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (228,'Ingeniero Publicaciones Tecnicas');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (229,'Lider Incorporacion Aviones Rutas y Estaciones');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (230,'Analista Venta a Bordo');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (231,'Coordinador CSA');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (232,'Jefe Operaciones Terrestres TIJ');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (233,'Representante Publicaciones Tecnicas');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (234,'Trabajador General Talleres');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (235,'Jefe Centro Control Operacional');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (236,'Director Planeacion de Rutas');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (237,'Lider Diseño Producto Digital');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (238,'Lider Ingenieria Sistemas');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (239,'Analista Resolucion y Monitoreo');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (240,'Lider Planeacion Financiera Flota');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (241,'Analista Administracion Activos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (242,'Especialista Informacion Estrategica Comercial');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (243,'Jefe Ingenieria Productos Digitales');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (244,'Lider Administracion Sistemas y Gestion Proveedores');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (245,'Gerente Sr Tecnologia Informacion');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (246,'Especialista Tecnologia Digital');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (247,'Especialista Estaciones Internacionales');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (248,'Analista Productos Digitales');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (249,'Gerente Sr Relaciones Laborales y BP Recursos Humanos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (250,'Lider Contabilidad Mantenimiento Linea');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (251,'Lider Capacitacion Corporativa');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (252,'Abogado Jr Contratos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (253,'Gerente Sr TI AMS');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (254,'Ingeniero Programa Mantenimiento');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (255,'Lider Transacciones Flota');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (256,'Instructor Mantenimiento');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (257,'Especialista Compras Indirectas');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (258,'Supervisor Abastecimiento Critico');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (259,'Lider Normatividad y Capacitacion');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (260,'Director Sr Financiamiento Corporativo y Relacion Inversionistas');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (261,'Lider Normatividad Contable');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (262,'Ingeniero Confiabilidad');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (263,'Analista Administracion Productos Adicionales');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (264,'Especialista Control Interno Administrativo y Financiero');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (265,'Especialista Plataforma y Sistemas');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (266,'Jefe Reclutamiento Administrativo');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (267,'Instructor Capacitacion Aeropuertos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (268,'Gerente Compensaciones y Beneficios');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (269,'Lider Regional Equipajes');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (270,'Gerente Relaciones Publicas');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (271,'Gerente Sr Transformacion');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (272,'Instructor Operaciones Aeropuerto');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (273,'Analista Equipajes');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (274,'Supervisor Taller');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (275,'Analista Customer Analytics');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (276,'Ingeniero Mantenimiento');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (277,'Jefe CSA');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (278,'Analista Centro de Contacto Solicitudes Publicas');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (279,'Especialista Administracion Liderazgo');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (280,'Lider Resolucion al Cliente');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (281,'Analista BI');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (282,'Especialista Gestion Procesos y Mejora Continua');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (283,'Lider CX Digital');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (284,'Vicepresidente Juridico');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (285,'Gerente Compras Indirectas');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (286,'Auxiliar Administrativo Reclutamiento');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (287,'Jefe Ingenieria Avionica y Sistemas');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (288,'Director Sr Planeacion Financiera y Contraloria');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (289,'Lider Customer Analytics');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (290,'Analista Seguridad Industrial y Medio Ambiente');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (291,'Gerente Mantenimiento');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (292,'Especialista Weather Desk');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (293,'Abogado Regulatorio Aviacion');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (294,'Investigador Seguridad Operacional');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (295,'Analista Informacion Financiera y Reporteo');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (296,'Analista Comercio Exterior');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (297,'Gerente Contabilidad Corporativa');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (298,'Gerente Sr Juridico Corporativo y Cumplimiento Bursatil');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (299,'Ingeniero Mantenimiento MEL');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (300,'Analista Gestion Comercial');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (301,'Analista Capacitacion Mantenimiento');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (302,'Capturista Registros Tecnicos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (303,'Jefe Programacion Mantenimiento');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (304,'Gerente Sr Comercial y Desarrollo Mercados MEX y USA');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (305,'Especialista Informacion Financiera y Reporteo');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (306,'Analista Travel');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (307,'Lider Travel');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (308,'Analista Grupos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (309,'Analista Planeacion Inventarios');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (310,'Capturista');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (311,'Especialista Flota');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (312,'Ingeniero Reparaciones');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (313,'Tecnico Seguridad Corporativa');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (314,'Jefe Regional Aeropuertos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (315,'Supervisor ACDM');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (316,'Analista Contratos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (317,'Especialista Planeacion Estrategica');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (318,'Analista Nomina');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (319,'Especialista Relacion con Inversionistas');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (320,'Analista Efectividad Organizacional');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (321,'Especialista Fiscal');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (322,'Gerente Data Analytics');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (323,'Especialista Capacitacion Corporativa');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (324,'Analista Servicios Generales');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (325,'Recepcionista');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (326,'Especialista Salud Ocupacional');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (327,'Analista Proyectos Planeacion Inmobiliaria');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (328,'Analista Planeacion Inmobiliaria');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (329,'Analista Registro Aeronaves');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (330,'Lider Seguros y Fianzas');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (331,'Gerente Relaciones Institucionales y Sustentabilidad');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (332,'Auditor Aseguramiento');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (333,'Aspirante Copiloto Becario');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (334,'Jefe Ventas Call Center');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (335,'Director Tesoreria y Finanzas Corporativas');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (336,'Especialista Slots');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (337,'Especialista Diseño Contenidos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (338,'Analista Registros Mandatorios');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (339,'Gerente Analisis y Reportes');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (340,'Especialista Medios');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (341,'Jefe Regional CAM');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (342,'Analista Itinerarios Corto Plazo y Publicacion');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (343,'Auxiliar Slots');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (344,'Chief of Staff DG');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (345,'Especialista BI');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (346,'Ingeniero EFB');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (347,'Especialista Comercio Exterior');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (348,'Analista Adiestramiento');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (349,'Ingeniero Rendimiento Aeronaves');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (350,'Analista Mantenimiento');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (351,'Analista FRMS');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (352,'Ingeniero Procedimientos y Normas DSP');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (353,'Analista CORSIA');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (354,'Analista IAMS');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (355,'Analista Compras Tecnicas');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (356,'Auxiliar Administrativo');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (357,'Lider Tarifa Base');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (358,'Ingeniero Procedimientos y Normas CAB');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (359,'Analista FDA');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (360,'Auditor Aseguramiento Calidad Mantenimiento');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (361,'Especialista Combustible');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (362,'Analista Aperturas');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (363,'Analista Call Center');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (364,'Especialista Call Center');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (365,'Ingeniero Incorporacion Aviones Rutas y Estaciones');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (366,'Analista Manejo Crisis');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (367,'Analista Estandares y Procedimientos AVSEC');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (368,'Gerente Aplicaciones Operacionales');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (369,'Jefe Sr Chief of Staff');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (370,'Ingeniero Procedimientos y Normas FLT');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (371,'Auditor Aseguramiento Calidad Operaciones');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (372,'Gerente Administracion Ingresos Internacionales');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (373,'Gerente Sr YaVas');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (374,'Analista QA Productos Digitales');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (375,'Especialista Seguridad Digital');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (376,'Analista CX Aeropuerto');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (377,'Jefe Capacitacion Pilotos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (378,'Lider Ingenieria Rendimiento Aeronaves');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (379,'Analista Airpas');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (380,'Analista Calidad Datos Airpas');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (381,'Analista Incidencias Airpas');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (382,'Auditor Sr Aseguramiento');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (383,'Analista Centro de Servicios RH');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (384,'Especialista Planeacion Adiestramiento');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (385,'Gerente Cadena Suministro y Logistica');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (386,'Analista Busqueda Talento');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (387,'Analista Modelos y Tarifa Base Dinamica');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (388,'Especialista Recuperacion e Inteligencia Datos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (389,'Especialista Planeacion Rosters A-SAV');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (390,'Asesor Sindical');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (391,'Gerente Sr Planeacion y Control Tripulaciones');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (392,'Abogado Jr');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (393,'Analista Customer Product Analytics');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (394,'Especialista Administracion Operaciones');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (395,'Analista Centro Control Operacional');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (396,'Especialista People Partner');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (397,'Especialista BI y Soporte');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (398,'Asistente Direccion');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (399,'Especialista Formacion');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (400,'Ingeniero Procedimientos y Normas GRH');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (401,'Auditor Financiero');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (402,'Auxiliar Planeacion Inmobiliaria');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (403,'Analista Diseño Producto Digital');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (404,'Analista Mantenimiento Linea');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (405,'Comprador Jr Indirectos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (406,'Analista Flota');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (407,'Director Recursos Humanos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (408,'Especialista Tesoreria');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (409,'Auditor');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (410,'Lider Erogaciones Productos y CONCUR');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (411,'Analista Planeacion Financiera Areas Administrativas');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (412,'Especialista UX Writing and Research');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (413,'Jefe Compras Indirectas Servicios Tecnologia y Comercial');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (414,'Jefe Compras Indirectas PI y Real Estate');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (415,'Analista Control Produccion');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (416,'Especialista Avionics');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (417,'Director Relacion con Inversionistas');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (418,'Gerente Operations Analytics');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (419,'Lider Planeacion Fiscal y Normatividad');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (420,'Analista Planeacion de Rutas');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (421,'Lider Financiamiento Corporativo');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (422,'Lider Erogaciones Aeropuertos Internacionales');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (423,'Especialista Cumplimiento Fiscal');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (424,'Especialista Redes Sociales');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (425,'Especialista Customer Analytics');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (426,'Trainee');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (427,'Vicepresidente de Reputacion y Desarrollo Corporativo');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (428,'Gerente Contratos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (429,'Jefe Sr Regulatorio');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (430,'Gerente Sr COE Capacitacion');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (431,'Analista Control Gestion Operaciones');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (432,'Gerente Proyectos Facilities y Planeacion Inmobiliaria');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (433,'Gerente Sr Efectividad Procesos y Analiticos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (434,'Especialista Reportes');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (435,'Analista Soporte Operaciones Vuelo');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (436,'Lider Aeropuerto TIJ');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (437,'Analista Capacitacion Tecnica');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (438,'Analista Portafolio Inversion');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (439,'Analista Performance Marketing');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (440,'Auxiliar Taller');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (441,'Aspirante Mecanico');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (442,'Especialista Servicios Generales');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (443,'Analista Ingenieria y Productos Digitales');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (444,'Analista Control Gestion Aeropuertos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (445,'Gerente Consumo Combustible');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (446,'Gerente Relacion Inversionistas');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (447,'Especialista Ingresos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (448,'Especialista Cuentas por Cobrar');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (449,'Especialista Facturacion');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (450,'Analista Hallazgos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (451,'Especialista Financiamiento Corporativo');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (452,'Lider IA');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (453,'Gerente Call Center');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (454,'Ejecutivo Ventas Carga');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (455,'Abogado Jr Regulatorio Aviacion');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (456,'Lider Tecnologia Ciberseguridad');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (457,'Especialista Planeacion Inventarios');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (458,'Analista Onboarding');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (459,'Especialista Otros Ingresos y Carga');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (460,'Gerente Planeacion Medios Digitales');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (461,'Analista Integridad Ingresos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (462,'Especialista Recursos Humanos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (463,'Especialista Diseño Producto Digital');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (464,'Especialista Compras Aeropuertos USA');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (465,'Auditor Jr Operaciones');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (466,'Analista Cumplimiento Aeropuertos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (467,'Gerente Sr Grupos Aeroportuarios, CAM y SAM');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (468,'Lider Procedimientos y Normas FLT');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (469,'Especialista Operaciones Digitales Ciberseguridad');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (470,'Comprador Jr Compras Indirectas PI y Real Estate');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (471,'Especialista Normatividad Contable');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (472,'Gerente Gestion Transformacion y Mejora Continua');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (473,'Jefe Sr Diseño Contenidos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (474,'Analista Soporte');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (475,'Lider Marketing Disruptivo CAM');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (476,'Lider Formas y Medios de Pago');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (477,'Analista Administracion y Finanzas');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (478,'Gerente Arquitectura TI');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (479,'Jefe Sr Financiamiento Corporativo');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (480,'Lider Consolidacion Contable');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (481,'Especialista Compras Conjuntas');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (482,'BP TI Operaciones Aerolinea');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (483,'Analista Transacciones Flota');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (484,'Auxiliar Onboarding');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (485,'Lider Base Pilotos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (486,'Especialista Tesoreria CAM y SAM');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (487,'Gerente Sr Mercadotecnia');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (488,'Lider Contenido');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (489,'Jefe Oficina Proyectos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (490,'Agente Trafico Becario');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (491,'Especialista Alianzas Digitales');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (492,'BP TI Operaciones Comerciales');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (493,'Jefe Sr Sobrecargos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (494,'Jefe Seleccion Pilotos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (495,'Jefe Erogaciones Flota y Administrativos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (496,'Jefe Sr Canales Distribucion y Trade Marketing');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (497,'Jefe Sr Planeacion Tripulaciones');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (498,'Jefe Solucion y Recuperacion al Cliente');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (499,'Gerente Sr Seguridad Corporativa y AVSEC');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (500,'Lider Administrativo Recursos Humanos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (501,'Jefe Sr Ingenieria Operaciones Vuelo');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (502,'Supervisor Control Calidad');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (503,'Director Aseguramiento Calidad y Seguridad Operacional');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (504,'Director Aeropuertos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (505,'Gerente Sr Productos Digitales');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (506,'Supervisor Estructuras');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (507,'Lider Capacitacion Aeropuertos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (508,'Jefe Sr Comercial Carga MEX');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (509,'Jefe Sr Carga Operativa');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (510,'Agente Coach Part Time');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (511,'Gerente Control Interno');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (512,'Especialista Canales de Distribucion y Alianzas');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (513,'Tecnico Mecanico Especialista');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (514,'Jefe Sr Tesoreria');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (515,'Director Talento y Desarrollo Organizacional');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (516,'Agente Coach Equipajes');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (517,'Jefe Sr Manejo Crisis');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (518,'Encargado Turno');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (519,'Gerente Sr Transacciones y Administracion Flota');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (520,'Lider Asignacion Corto Plazo');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (521,'Lider Weather Desk');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (522,'Jefe Regional Pilotos Oeste');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (523,'Ingeniero Rotables');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (524,'Jefe Aplicaciones Operaciones');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (525,'Supervisor Mantenimiento Hangar');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (526,'Lider Desarrollo Soluciones');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (527,'Lider Grupos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (528,'Jefe Operaciones Terrestres GDL');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (529,'Especialista Entretenimiento a Bordo');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (530,'Especialista Mercadotecnia');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (531,'Jefe Sr ACDM');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (532,'Lider Portafolio Inversion');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (533,'Lider Archivo Tecnico');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (534,'Jefe Confiabilidad');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (535,'Lider Itinerarios Corto Plazo y Publicacion');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (536,'Gerente Cumplimiento Fiscal');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (537,'Gerente Pricing');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (538,'Lider Itinerarios Largo Plazo');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (539,'Jefe Sr Asignacion Flota');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (540,'Vicepresidente Ejecutivo Aerolinea - Comercial y Operaciones');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (541,'Gerente Aeropuerto GDL');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (542,'Lider Planeacion Pairing and Rostering');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (543,'Jefe Sr Aeropuerto AICM');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (544,'Gerente Aseguramiento Calidad');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (545,'Gerente Sr Canales Distribucion y Alianzas');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (546,'Jefe Sr Administracion de Ingresos Domesticos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (547,'Jefe Sr Tesoreria Contable');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (548,'Jefe Publicaciones Tecnicas');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (549,'Especialista Seguridad Informacion');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (550,'Analista Direccion General');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (551,'Lider LMS');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (552,'Lider Estandares Servicio al Cliente');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (553,'Coordinador Operaciones Terrestres AICM');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (554,'Gerente Mantenimiento Linea');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (555,'Jefe Sr Control Tripulaciones');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (556,'Lider Procedimientos y Normas GSO CAB y GRH');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (557,'Gerente Nomina');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (558,'Jefe Sr Soporte Operativo MEX');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (559,'Jefe Mantenimiento Estaciones');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (560,'Coordinador Slots y Manifiestos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (561,'Lider Nomina');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (562,'Jefe Centro Servicios RH');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (563,'Supervisor Recibo e Inspeccion');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (564,'Jefe BP Recursos Humanos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (565,'Gerente Informacion Financiera y Reporteo');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (566,'Director Sr Operaciones');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (567,'Director Auditoria Interna y Evaluacion de Riesgos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (568,'Jefe Soporte Operativo GDL');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (569,'Jefe Capacitacion Mantenimiento');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (570,'Gerente Planeacion y Administracion Flota');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (571,'Lider Digital Customer Care');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (572,'Gerente Sr Administracion Productos Adicionales');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (573,'Gerente Sr Administracion Ingresos y Pricing');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (574,'Jefe Cuentas por Cobrar y Carga');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (575,'Instructor AVSEC');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (576,'Jefe Ingresos Corporativos y Facturacion');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (577,'Gerente Mantenimiento CAM');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (578,'Jefe Regional Pilotos Centro');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (579,'Lider Continuidad Negocio y ERM');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (580,'Jefe Salud Ocupacional');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (581,'LIder Recuperacion e Inteligencia Datos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (582,'Jefe Aeropuerto GDL');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (583,'Gerente Sr Aeropuertos HUBs');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (584,'Lider Navegacion');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (585,'Especialista Equipajes Sistema');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (586,'Lider Administracion Tecnica Arrendamientos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (587,'Lider Seguridad Aeroportuaria');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (588,'Jefe Sr Aeropuerto Internacional');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (589,'Gerente Grupos e Integridad Ingresos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (590,'Jefe Aseguramiento Calidad Mantenimiento');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (591,'Especialista Estandares Servicio a Bordo');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (592,'Digital Disruption Management Analyst');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (593,'Jefe Sr Administracion Tripulaciones');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (594,'Jefe Sr Recursos Humanos CAM SAM');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (595,'Jefe Combustible');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (596,'Jefe Sr BP Recursos Humanos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (597,'Analista Cumplimiento Aeropuertos A-SAV');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (598,'Jefe Aplicaciones Mantenimiento');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (599,'Analista Control Sistema');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (600,'Gerente Cultura y Comunicacion');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (601,'Jefe Sr Equipajes Sistema');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (602,'Lider Aeropuerto MTY');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (603,'Lider Aeropuerto GDL');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (604,'Especialista Productos Digitales');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (605,'Vicepresidente Sr Administracion y Finanzas');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (606,'Director Planeacion Financiera y Control Gestion');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (607,'Especialista Estaciones Nacionales');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (608,'Especialista SAP');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (609,'Jefe Logistica');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (610,'Jefe Compras Aeropuertos Internacionales');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (611,'Gerente Erogaciones');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (612,'Analista Plataforma Microsoft');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (613,'Ingeniero Operaciones Vuelo');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (614,'Coordinador Planeacion Inventarios');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (615,'Lider CAM y Otros Ingresos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (616,'Gerente Estrategia Comercial y Mercado');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (617,'Gerente Sr Tesoreria y Medios de Pago');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (618,'Gerente Gobierno Corporativo');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (619,'Jefe Reclutamiento Operaciones Vuelo');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (620,'Jefe Almacen Tecnico');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (621,'Jefe Sr SMS y FDA');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (622,'Especialista Asignacion Flota');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (623,'Coordinador Reparaciones');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (624,'Especialista Manejo Crisis');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (625,'Gerente Sr Control Gestion');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (626,'Jefe Formas y Medios de Pago');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (627,'Supervisor Avionica');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (628,'Coordinador Almacen Tecnico');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (629,'Gerente Seguridad TI');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (630,'Lider Reportes');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (631,'Lider Productos Digitales');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (632,'Coordinador Comercio Exterior');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (633,'Lider Contabilidad Mantenimiento Mayor');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (634,'Lider de Gestion de Procesos y Mejora Continua');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (635,'Jefe Relaciones Laborales');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (636,'Analista Administracion GHA');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (637,'Jefe Ingenieria Estructuras e Interiores');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (638,'Lider Seguridad Operacional');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (639,'Lider Informacion Estrategica');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (640,'Lider Control Calidad Despacho');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (641,'Supervisor Abastecimiento');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (642,'Especialista AVSEC');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (643,'Auditor Sr Aseguramiento TI');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (644,'Gerente Auditoria TI');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (645,'Lider Aperturas');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (646,'Lider Infraestructura');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (647,'Especialista Planeacion Financiera Mantenimiento');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (648,'Analista Administrativo LMS');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (649,'Lider Analisis');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (650,'Especialista Planeacion Rosters');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (651,'Jefe Planeacion Inventarios y Reparaciones');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (652,'Coordinador Compras Tecnicas');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (653,'Especialista Gestion Proveedores');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (654,'Lider Cloud y Data Center');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (655,'Lider Planeacion de Rutas');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (656,'Analista Procesos Roster y Mejora Continua');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (657,'Jefe Sr Juridico CAM');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (658,'Gerente Sr Digital Customer Care');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (659,'Supervisor NDT');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (660,'Especialista Apertura y Cierres Infraestructura');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (661,'Gerente Socio Talento Operativo');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (662,'Especialista Control Gestion IT y Customer Delivery');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (663,'Lider Erogaciones Combustible');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (664,'Director Sr Mantenimiento');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (665,'Jefe Sr Contabilidad General');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (666,'Especialista BP TI');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (667,'Lider Investigacion Operaciones');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (668,'Lider Servicios Generales');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (669,'Gerente Sr Aseguramiento y Evaluacion de Riesgos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (670,'Jefe Analisis Datos Comercial');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (671,'Especialista Estructuras');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (672,'Ingeniero Manuales');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (673,'Jefe Operaciones Terrestres CUN');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (674,'Especialista Calidad Pruebas');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (675,'Director Ingenieria y Planeacion');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (676,'Lider Control Interno Operativo y Mantenimiento');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (677,'Lider Ingenieria Avionica');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (678,'Jefe Administracion Talento');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (679,'Especialista Comunicacion Institucional');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (680,'Jefe Manuales y Procedimientos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (681,'Lider Cumplimiento Fiscal Internacional');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (682,'Coordinador Cumplimiento Aeropuertos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (683,'Lider Optimización y Analisis Datos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (684,'Jefe Centro Control Mantenimiento');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (685,'Especialista Aplicaciones Mantenimiento');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (686,'Especialista Contratos Pool Partes Auditoria');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (687,'Especialista Soporte Apps');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (688,'Jefe Programa Mantenimiento');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (689,'Lider Administracion Sobrecargos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (690,'Gerente Itinerarios');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (691,'Jefe Calidad y Medio Ambiente');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (692,'Lider Asignacion Mediano y Largo Plazo');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (693,'Lider Registros Mandatorios');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (694,'Lider Capacitacion Recurrente Sobrecargos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (695,'Gerente Sr Sobrecargos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (696,'Jefe BI y Gobierno Datos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (697,'Lider Aeropuerto CUN');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (698,'Lider Administracion Pilotos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (699,'Lider Ingenieria W&B');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (700,'Especialista Control Gestion Mantenimiento');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (701,'Lider Contabilidad');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (702,'Jefe Aeropuerto CUN');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (703,'Analista Administracion Aeropuertos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (704,'Especialista Control Gestion de Mantenimiento');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (705,'Gerente Control Gestion Aeropuertos FAS AVSEC');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (706,'Gerente Planeacion Mantenimiento');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (707,'Gerente Ingenieria Mantenimiento');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (708,'Jefe Efectividad Organizacional');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (709,'Lider Beneficios');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (710,'Coordinador Proyectos Planeacion Inmobiliaria');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (711,'Especialista Contabilidad');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (712,'Lider FDA');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (713,'Jefe Sr Hub Control');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (714,'Reclutador Sr');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (715,'Gerente Sr Centro Control Operacional');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (716,'Especialista Capacitacion Tecnica');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (717,'Jefe Taller Estacion Reparadora');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (718,'Especialista Onboarding');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (719,'Analista Logistica');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (720,'Especialista Planeacion y Administracion Flota');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (721,'Lider Comercial');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (722,'Gerente Seguridad Informacion y Control Interno TI');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (723,'Jefe Aseguramiento Calidad Operaciones');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (724,'Gerente Socio Talento Administrativo y CAM SAM');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (725,'Lider Control Gestion Operaciones Vuelo');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (726,'Jefe Sr Compras Combustible');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (727,'Abogado Sr Contratos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (728,'Lider Soporte Operaciones Vuelo');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (729,'Especialista Registro Componentes');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (730,'Gerente Control Calidad');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (731,'Lider Comisariato MX y CAM');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (732,'Jefe Reclutamiento Operaciones Tierra');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (733,'Gerente Estrategia');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (734,'Supervisor Planeacion Inventarios');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (735,'Gerente Sr Compensaciones y Efectividad Organizacional');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (736,'Lider Administración de Productos Adicionales');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (737,'Especialista Centro Servicios RH');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (738,'Jefe Servicio Venta a Bordo');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (739,'Lider Contable YaVas');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (740,'Analista Procesos y Control Interno TI');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (741,'Lider Proyectos Planeacion Inmobiliaria y Real Estate');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (742,'Gerente Control Gestion Mantenimiento');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (743,'Analista Soporte Aplicaciones Bases Datos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (744,'Especialista Compras Aeropuertos MEX');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (745,'Especialista Capacitacion Servicio al Cliente');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (746,'Especialista Seguridad Cibernetica');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (747,'Gerente Regional Aeropuertos ASA, Sociedades, CAM y SAM');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (748,'Gerente Regional Aeropuertos ASUR y OMA');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (749,'Gerente Servicio a Bordo');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (750,'Gerente Sr Administracion Riesgos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (751,'Especialista Control Gestion Aeropuertos Domésticos y AVSEC');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (752,'Jefe Control Gestion Comercial Administrativo e IT');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (753,'Auditor Aseguramiento TI');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (754,'Lider Seguros y Fianzas Aviones');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (755,'Lider Estandares Vuelo');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (756,'Especialista TI');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (757,'Ayudante Soporte Tecnico');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (758,'Especialista Seguridad Industrial y Medio Ambiente');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (759,'Auditor Sr Analiticos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (760,'Supervisor Logistica');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (761,'Especialista Regional Equipajes');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (762,'Lider Administracion Peticiones y Aclaraciones');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (763,'Lider Planeacion Linea');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (764,'Analista BP');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (765,'Lider Administracion Ingresos Domesticos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (766,'Especialista Registro Motores');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (767,'Gerente Sr Carga');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (768,'Analista Planeacion Rosters');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (769,'Jefe Compras Tecnicas');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (770,'Gerente Ventas y Desarrollo Mercados USA');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (771,'Especialista Compensaciones y Proyectos SAP');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (772,'Especialista Compensaciones');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (773,'Lider Control Gestion Combustible');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (774,'Especialista Estandares Canales Comunicacion');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (775,'Jefe Administracion Proyectos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (776,'Lider Capacitacion Servicio al Cliente');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (777,'Especialista Compliance');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (778,'Especialista Customer Product Analytics');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (779,'Especialista Capacidad Carga');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (780,'Especialista Dynamic Pricing');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (781,'Jefe Sr Producto YaVas');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (782,'Gerente End User Services');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (783,'Jefe Sr Erogaciones');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (784,'Analista Aseguramiento Calidad y Seguridad Operacional');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (785,'Jefe Sustentabilidad');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (786,'Jefe Contenido');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (787,'Analista Patrocinios y Aeropuertos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (788,'Especialista Travel Protecciones');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (789,'Jefe Sr Marketing');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (790,'Gerente Planeacion Estrategica y Desarrollo Negocios');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (791,'Director Mercadotecnia y Digital');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (792,'Especialista Administracion Ingresos Internacionales');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (793,'Jefe Compras Aeropuertos Nacionales');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (794,'Lider Modelos y Tarifa Base Dinamica');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (795,'Analista Estrategia y Proyectos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (796,'Gerente Sr Finanzas Corporativas y Riesgos');
INSERT INTO `volaris`.`positions` (`id`,`name`) VALUES (797,'Analista Informacion Estrategica Operaciones');
